AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: VPBank StreamGuard - Serverless Fraud Detection API

Globals:
  Function:
    Timeout: 10
    MemorySize: 512
    Runtime: python3.11
    Architectures:
      - x86_64
    Environment:
      Variables:
        LOG_LEVEL: INFO

Resources:
  # DynamoDB Table for Entity Risk
  EntityRiskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: vpbank-entity-risk
      BillingMode: PAY_PER_REQUEST  # Auto-scaling
      AttributeDefinitions:
        - AttributeName: entity_key
          AttributeType: S
      KeySchema:
        - AttributeName: entity_key
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false  # Save costs
      Tags:
        - Key: Project
          Value: VPBank-StreamGuard
        - Key: Environment
          Value: Production

  # S3 Bucket for Models
  ModelBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub vpbank-fraud-models-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30
      Tags:
        - Key: Project
          Value: VPBank-StreamGuard

  # Lambda Execution Role
  FraudScoringFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3ModelAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !GetAtt ModelBucket.Arn
                  - !Sub ${ModelBucket.Arn}/*
        - PolicyName: DynamoDBEntityRiskAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                Resource: !GetAtt EntityRiskTable.Arn

  # Lambda Function
  FraudScoringFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: vpbank-fraud-scoring
      CodeUri: lambda/
      Handler: handler.lambda_handler
      Role: !GetAtt FraudScoringFunctionRole.Arn
      Environment:
        Variables:
          MODEL_BUCKET: !Ref ModelBucket
          MODEL_KEY: fast_lane/lr_model.pkl
          SCALER_KEY: fast_lane/scaler.pkl
          ENTITY_RISK_TABLE: !Ref EntityRiskTable
      Events:
        PredictAPI:
          Type: Api
          Properties:
            Path: /predict
            Method: post
            RestApiId: !Ref FraudAPI
        HealthAPI:
          Type: Api
          Properties:
            Path: /health
            Method: get
            RestApiId: !Ref FraudAPI

  # API Gateway
  FraudAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: vpbank-fraud-api
      StageName: prod
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Api-Key,Authorization'"
        AllowOrigin: "'*'"
      Auth:
        ApiKeyRequired: false  # Enable later for production
      TracingEnabled: true
      MethodSettings:
        - ResourcePath: /*
          HttpMethod: '*'
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true

  # CloudWatch Log Group
  FraudScoringFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${FraudScoringFunction}
      RetentionInDays: 7  # Reduce costs

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub https://${FraudAPI}.execute-api.${AWS::Region}.amazonaws.com/prod
    Export:
      Name: VPBank-FraudAPI-URL

  PredictEndpoint:
    Description: Fraud prediction endpoint
    Value: !Sub https://${FraudAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/predict

  HealthEndpoint:
    Description: Health check endpoint
    Value: !Sub https://${FraudAPI}.execute-api.${AWS::Region}.amazonaws.com/prod/health

  FunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt FraudScoringFunction.Arn

  TableName:
    Description: DynamoDB table name
    Value: !Ref EntityRiskTable

  BucketName:
    Description: S3 bucket name for models
    Value: !Ref ModelBucket
